version: "3.8"
services:
  nginx:
    build:
      context: .
    ports:
      - 3000:80
    volumes:
      - ../../frontend-reactjs/build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    # docker compose -p nginx up -d
